services:
  infinispan:
    image: quay.io/infinispan/server:15.2
    command: -c infinispan.xml -b 0.0.0.0
    ports:
      - 11222:11222
    volumes:
      - ./infinispan.xml:/opt/infinispan/server/conf/infinispan.xml:ro
      - infinispan_data:/opt/infinispan/server/data

  ollama:
    image: docker.io/ollama/ollama:latest
    ports:
      - 11434:11434
    volumes:
      - ollama_data:/root/.ollama

  qdrant:
    image: docker.io/qdrant/qdrant:v1.14.1
    ports:
      - 6333:6333
      - 6334:6334
    volumes:
      - qdrant_storage:/qdrant/storage

volumes:
  infinispan_data:
  ollama_data:
  qdrant_storage:
